### ISSUE TITLE
gemでのインストールについて

### ISSUE THREAD

**Issue by ksato9700** [takahashim/aozora2html#1]
gemでのインストールを試みたのですが、見つからないと言われてしまいます。

$ gem install aozora2html
ERROR:  Could not find a valid gem 'aozora2html' (>= 0) in any repository

gem 2.4.5 (ruby 2.2.2p95) と gem 1.8.23.2 (ruby 1.9.3p551) で試しましたが同じ結果でした。

また、rubygems.orgでの検索結果でも同様でした。
https://rubygems.org/search?query=aozora2html

何か追加で設定など必要だったでしょうか。
よろしくお願いします。

**Comment by takahashim** [comment]
すみません！　こちらリリースをまだしてないので、rubygems.orgからはインストールできないのでした…。
aozorahack oraganizationに持っていってからリリースしようと思っていたのですが、そのままになっていたので、近々に何とかします。お待たせしてすみません。

**Comment by ksato9700** [comment]
あ、そうだったんですね。早とちりしました。申し訳ありません。ソースからのインストールで試しているので全然急ぎません。是非お時間のあるときにでも。

**Comment by takahashim** [comment]
@ksato9700 大変お待たせしました、こちら対応しました！
https://rubygems.org/gems/aozora2html

ちなみにリポジトリは https://github.com/aozorahack/aozora2html の方に移行しました。ご了承ください（なんかうまく引き継げませんでした…。あとでこちらのレポジトリの方を作りなおすかもです）。
