### ISSUE TITLE
手元でのPreviewについて

### ISSUE THREAD

**Issue by ksato9700** [takahashim/aozora2html#5]
もう一つご相談させて下さい。Aozora形式のテキストをaozora2htmlでhtmlに変換し、それをブラウザで見てもうまくレンダリングされません。理由は、そのHTMLから参照されているスタイルシートなどのファイルが読み込めないからだと思います。具体的には、"../../" という相対パスにそれらファイルがある前提になっていて、aozora.gr.jpに置かない限り(あるいは同じ階層に自分で必要なファイルを置く事をしない限り)、読み込まれません。

入力者および校正者が作業される上で、手元で表示確認できると良いと思うのですが、どのようにするのが良いと思われますか？実際、自分も工作員として入力をしていたりするのですが、プレビュー機能が欲しくなります。

試しにksato9700/aozora2html でローカルのサーバ立てて../../へのアクセスはaozora.gr.jpにredirectするというツールを作ってみたりしていますが、すでに@takahashim さんに構想などあればお聞かせいただきたく

**Comment by takahashim** [comment]
あー、なるほど。
相対パスについては、基本は「同じ階層に自分で必要なファイルを置く」を推奨というか、`t2hs.rb`については極力いじらず同じ環境で動かす方が安全だとは思うのですが、`t2hs.rb`の外で上書きすることはできるかもしれません。後で確認してみます。

**Comment by takahashim** [comment]
@ksato9700 こちらも大変お待たせしてしまってすみません、 https://github.com/aozorahack/aozora2html/pull/4 で、オプションで画像パスを指定できるようにしてみました。これでいかがでしょうか。

**Comment by ksato9700** [comment]
済みません、こちらOpenのままでしたね。aozorahack/aozora2html#4　でコメントしたようにその対応で問題なく手元でプレビュー出来るようになりました。ありがとうございました。
